name: asap
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_0
  - blas=1.0=openblas
  - boto=2.48.0=py36hdbc59ac_1
  - boto3=1.7.24=py36_0
  - botocore=1.10.24=py36_0
  - bz2file=0.98=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36h342bebf_0
  - chardet=3.0.4=py36h96c241c_1
  - cryptography=2.2.2=py36h1de35cc_0
  - cymem=1.31.2=py36_0
  - cytoolz=0.8.2=py36h290905f_0
  - dill=0.2.7.1=py36hdf89ffe_0
  - docutils=0.14=py36hbfde631_0
  - ftfy=4.4.3=py36_0
  - gensim=3.4.0=py36h917ab60_0
  - html5lib=1.0.1=py36h2f9c1c0_0
  - idna=2.6=py36h8628d0a_1
  - intel-openmp=2018.0.0=8
  - jmespath=0.9.3=py36h767a2d6_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libopenblas=0.2.20=hdc02c5d_7
  - mkl=2018.0.2=1
  - msgpack-numpy=0.4.1=py36h98f623a_0
  - msgpack-python=0.4.8=py36h46767b2_0
  - murmurhash=0.28.0=py36_0
  - ncurses=6.1=h0a44026_0
  - numpy=1.14.3=py36he6379a5_2
  - numpy-base=1.14.3=py36h9797aa9_2
  - openssl=1.0.2o=h26aff7b_0
  - pandas=0.23.0=py36h1702cab_0
  - pip=10.0.1=py36_0
  - plac=0.9.6=py36_0
  - preshed=1.0.0=py36_0
  - pycparser=2.18=py36h724b2fc_1
  - pyopenssl=18.0.0=py36_0
  - pysocks=1.6.8=py36_0
  - python=3.6.5=hc167b69_1
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.4=py36_0
  - readline=7.0=hc1231fa_4
  - regex=2017.11.09=py36hb672b4b_0
  - requests=2.18.4=py36h4516966_1
  - s3transfer=0.1.13=py36_0
  - scikit-learn=0.19.1=py36hffbff8c_0
  - scipy=1.1.0=py36hcaad992_0
  - setuptools=39.2.0=py36_0
  - six=1.11.0=py36h0e22d5e_1
  - smart_open=1.5.7=py36_0
  - spacy=2.0.11=py36h1702cab_0
  - sqlite=3.23.1=hf1716c9_0
  - termcolor=1.1.0=py36_1
  - thinc=6.10.2=py36h1702cab_0
  - tk=8.6.7=h35a86e2_3
  - toolz=0.9.0=py36_0
  - tqdm=4.23.4=py36_0
  - ujson=1.35=py36_0
  - urllib3=1.22=py36h68b9469_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36h3b9701d_1
  - wheel=0.31.1=py36_0
  - wrapt=1.10.11=py36hc29e774_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=hf3cbc9b_2
  - pip:
    - en-core-web-sm==2.0.0
    - lightgbm==2.1.1
    - ml-metrics==0.1.4
    - when-will-it-end==0.0.2
prefix: /Users/me/miniconda/envs/asap

